### Task 1
Create a 1D array of numbers from 0 to 9



In [256]:
import numpy as np
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Task 2
Create a 3×3 NumPy array of all Boolean value Trues

In [257]:
my_array = np.ones(9, dtype=bool).reshape(3,3)
my_array


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Task 3
Extract all odd numbers from array of 1-10


In [258]:
my_array = np.arange(1,11)
odd_nums = my_array[::2]
odd_nums

# alternatively created using arange function
# odds_ARRAY = np.arange(1,11, 2)
# odds_ARRAY


array([1, 3, 5, 7, 9])

### Task 4
Replace all odd numbers in an array of 1-10 with the value -1


In [259]:
my_array = np.arange(1,11)
my_array[::2]= -1
my_array


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

### Task 5
Convert a 1D array to a 2D array with 2 rows


In [260]:
my_array = np.arange(1,21).reshape(2,-1)
my_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

### Task 6
Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

In [261]:
np.random.seed(seed=42)

a = np.random.rand(1,20)
a = a.reshape(4, 5)
b = np.random.rand(1,20)
b = b.reshape(5, 4)

vert_stack = np.vstack((a, b.reshape(4,5)))
vert_stack

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
       [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249]])

In [262]:
print(f"Shape of a: {a.shape}, Shape of b: {b.shape}, Num_elements: {a.size}. We will get a 4 by 4 matrix")
dot_prod = np.dot(a,b)
dot_prod


Shape of a: (4, 5), Shape of b: (5, 4), Num_elements: 20. We will get a 4 by 4 matrix


array([[1.1828687 , 1.41602254, 1.42880868, 1.3035558 ],
       [0.8898634 , 0.74714866, 1.64835415, 1.03232265],
       [1.01729199, 1.02233336, 1.03487755, 0.89993906],
       [0.67865681, 0.727154  , 1.04951146, 0.79049632]])

In [263]:
print(a.sum(), b.sum()) # sum of all elements in each matrix
print(a.sum(axis=0), b.sum(axis = 0))  # sums of the individual matrices on columns
print(a.sum(axis=1), b.sum(axis=1))  # sums of the individual matrices  on rows

c = a + b.reshape(4, 5) # added the matrices as was not sure if you meant the sums of the combined matrices a and b
c_tot_ax0 = np.sum(c, axis=0)
c_tot_ax1 = np.sum(c, axis=1)

print(c_tot_ax0, c_tot_ax1)  # not sure if you wanted the sums of the matrixes combined

9.15404576795571 9.096579285417269
[0.73452364 2.28295001 2.95536916 1.84405763 1.33714533] [2.03000281 2.01767789 2.74922834 2.29967025]
[2.81192549 2.38944187 2.21710107 1.73557734] [1.40985325 1.95515417 1.41693396 2.78796651 1.5266714 ]
[3.5474947  3.09725555 3.92447195 4.4359526  3.24545025] [4.67784872 4.52739103 4.9747392  4.07064609]


### Task 7
Create the following pattern without hardcoding. Use only NumPy  functions.
1.  array( 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, )



In [264]:
ones  = np.ones(3)
twos = np.ones(3) * 2
threes = np.ones(3) * 3
onesToThree = np.tile([1, 2, 3], 3) # repeats 123 three times

my_new_array = np.hstack((ones, twos, threes, onesToThree)) # concatenates the 111, 222, 333 with the 123 repeated
my_new_array

array([1., 1., 1., 2., 2., 2., 3., 3., 3., 1., 2., 3., 1., 2., 3., 1., 2.,
       3.])

### Task 8

In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b


In [265]:
a = np.array(list(range(1,6)))
b = np.array(list(range(4,10)))
c = np.union1d(a, b)
print(c)

[1 2 3 4 5 6 7 8 9]


### Task 9
Get all items between 3 and 7 from a and b and sum them together


In [266]:
items3to7 = c[2:7]

print(f"items 3 to 7: {items3to7},  SUM IS : {np.sum(items3to7)}" )

items 3 to 7: [3 4 5 6 7],  SUM IS : 25
